configMapGenerator:
- envs:
  - config.properties
  name: backplane-example-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
- ../kustomization.yaml
patches:
- path: replicas.yaml
