apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backplane-appsets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: https://github.com/reifyhealth/argo-examples
    targetRevision: main
    path: appset
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    

    