
patchesStrategicMerge:
- replicas.yaml

configMapGenerator:
- envs:
  - config.properties
  name: mykustom-map
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
images:
- name: devopsjourney1/mywebapp
  newTag: latest_use1
