apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 519400232874.dkr.ecr.us-east-1.amazonaws.com/backplane-example-service
  newTag: 037b7dacb9a512194c6ff3d6d1586e99c9072f73
