resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1

images:
  - name: mycontainer
    newName: devopsjourney1/mywebapp
    newTag: wwwwwww