patches:
- path: replicas.yaml

configMapGenerator:
- envs:
  - config.properties
  name: backplane-example-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/dunnjt/argo-version/version
