configMapGenerator:
- envs:
  - config.properties
  name: backplane-example-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../version
- https://github.com/dunnjt/argo-version/version?ref=main
patches:
- path: replicas.yaml
