apiVersion: apps/v1
kind: Deployment
metadata:
  name: backplane-example
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: ""
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backplane-example
        resources:
          requests:
            memory: "128Mi" 
            cpu: "1"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "512Mi"
            cpu: "2"