resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: backplane-example

commonAnnotations:
  app: mykustom-annontations

namePrefix: kustom-

nameSuffix: -v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 519400232874.dkr.ecr.us-east-1.amazonaws.com/backplane-example-service
  newTag: snapshot.8b37413c46351e98b363e6625eacea80b88e6841_test2
